### ISSUE TITLE
gulp serve failing on Windows 10 x64

### ISSUE THREAD

**Issue by avitevet** [jakearchibald/idb#12]
I'm trying to use idb on Windows for a Udacity project, but I can't even get gulp serve to succeed.  Can you please tell me what I can do so that I can run gulp serve?

```
C:\Users\avite\OneDrive\Documents\github\idb>npm --version
3.10.8

C:\Users\avite\OneDrive\Documents\github\idb>node --version
v6.9.1

C:\Users\avite\OneDrive\Documents\github\idb>git log -n 1
commit 314309cf7ed3db66468a0d12e31663904dcc59f9
Author: Jake Archibald <jaffathecake@gmail.com>
Date:   Fri Aug 12 14:00:31 2016 +0100

    README consistency

C:\Users\avite\OneDrive\Documents\github\idb>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

C:\Users\avite\OneDrive\Documents\github\idb>gulp serve
[21:33:57] Using gulpfile ~\OneDrive\Documents\github\idb\gulpfile.js
[21:33:57] Starting 'serve'...
[21:33:57] Starting 'clean'...
[21:33:57] Finished 'clean' after 196 ms
[21:33:57] Starting 'copy'...
[21:33:57] Starting 'js'...
[21:33:58] Starting 'copy-lib'...
[21:33:58] Finished 'copy-lib' after 238 ms
[21:33:58] Finished 'copy' after 714 ms
[21:33:58] Browserify Error { Error: Cannot find module 'babelify/node_modules/babel-core/node_modules/regenerator/runtime' from 'C:\Users\avite\OneDrive\Documents\github\idb\test'
    at C:\Users\avite\OneDrive\Documents\github\idb\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\avite\OneDrive\Documents\github\idb\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\avite\OneDrive\Documents\github\idb\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\avite\OneDrive\Documents\github\idb\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\avite\OneDrive\Documents\github\idb\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\avite\OneDrive\Documents\github\idb\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
  stream:
   Labeled {
     _readableState:
      ReadableState {
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: true,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: true,
     domain: null,
     _events:
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        highWaterMark: 16,
        objectMode: true,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [],
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: true,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object] ],
     length: 1,
     label: 'deps' } }
```

**Comment by jakearchibald** [comment]
You don't need to use gulp serve in this repo as part of the Udacity project. It's already included with Wittr.

**Comment by avitevet** [comment]
Thanks... I was going to do headless testing with phantomjs using this lib in my transportation app, but I was getting indexedDB errors.  Eventually I decided that instead of drilling into indexedDB, I would switch to slimerjs, which is gecko-based and has much better support for IndexedDB (and promises, for that matter).  The same code that was failing in phantomjs is now passing in slimerjs, so I don't need to dig in to indexedDB issues anymore.
