### ISSUE TITLE
unable to import idb into react component

### ISSUE THREAD

**Issue by noahehall** [jakearchibald/idb#17]
working on project 2 of udacity course

see relevant code here:
https://github.com/noahehall/udacity-trainschedule/blob/indexeddb/src/containers/start/start.js

if i attempt to 
`import IdbKeyval from 'serviceworkers/idb/idb';`

it throws error
`
/Users/halln/git/udacity/projects/trainschedule/dist/server.js:20898
  proxyRequestMethods(Index, '_index', IDBIndex, [
                                       ^

ReferenceError: IDBIndex is not defined
    at /Users/halln/git/udacity/projects/trainschedule/dist/server.js:20898:40
    at Object.__dirname./Users/halln/git/udacity/projects/trainschedule/node_modules/idb/lib/idb.js (/Users/halln/git/udacity/projects/trainschedule/dist/server.js:21114:2)
    at s (/Users/halln/git/udacity/projects/trainschedule/dist/server.js:1:316)
    at /Users/halln/git/udacity/projects/trainschedule/dist/server.js:1:367
    at Object.__dirname./Users/halln/git/udacity/projects/trainschedule/src/serviceworkers/idb/idb.js.../../constants.js (/Users/halln/git/udacity/projects/trainschedule/dist/server.js:94623:12)
    at s (/Users/halln/git/udacity/projects/trainschedule/dist/server.js:1:316)
    at /Users/halln/git/udacity/projects/trainschedule/dist/server.js:1:367
    at Object.__dirname./Users/halln/git/udacity/projects/trainschedule/src/containers/start/start.js.../../components/forms/forms.js (/Users/halln/git/udacity/projects/trainschedule/dist/server.js:93753:12)
    at s (/Users/halln/git/udacity/projects/trainschedule/dist/server.js:1:316)
    at /Users/halln/git/udacity/projects/trainschedule/dist/server.js:1:367
`

However, it works perfectly in service worker context

im trying to do what this guy did here:
https://github.com/nreoch25/react-redux-indexeddb/blob/master/app/components/Arts.js

and retrieve items from indexedb and inject them into redux store

**Comment by noahehall** [comment]
if i import conditionally it works, but it seems too much of a hack 

<img width="753" alt="screen shot 2016-11-23 at 3 49 07 pm" src="https://cloud.githubusercontent.com/assets/10324554/20582264/8129851a-b194-11e6-942a-706495a240cf.png">
