### ISSUE TITLE
`done` promise semantics is confusing and may cause uncaught promise rejections

### ISSUE THREAD

**Issue by golergka** [jakearchibald/idb#320]
**Is your feature request related to a problem? Please describe.**

The way that `done` promise currently works causes uncaught errors for us. Let's take this piece of code as an example:

```Typescript
try {
  const tx = db.transaction(storeName, "readwrite");
  await tx.store.add(value);
  await tx.done;
} catch (error) {
  console.error(error); // we expect the errors to be caught here
}
```

From the documentation and just naive intuition about how the code works, I would expect that if add operation fails, I would catch the error. However, when I trigger this failure in Jest, I get this:

```
 FAIL  src/background/idb/storage.test.ts
  ● storage › IngestionStore › should not add duplicate events and log an error

    AbortError: AbortError

      at FDBTransaction.error (../../../node_modules/idb/build/index.cjs:70:32)
      at invokeEventListeners (../../../node_modules/fake-indexeddb/build/cjs/lib/FakeEventTarget.js:25:23)
      at FDBRequest.dispatchEvent (../../../node_modules/fake-indexeddb/build/cjs/lib/FakeEventTarget.js:97:11)
      at FDBTransaction._start (../../../node_modules/fake-indexeddb/build/cjs/FDBTransaction.js:179:19)
      at ../../../node_modules/fake-indexeddb/build/cjs/lib/Database.js:31:16
      at run (../../../node_modules/setimmediate/setImmediate.js:40:13)
      at runIfPresent (../../../node_modules/setimmediate/setImmediate.js:69:21)
      at Timeout.task [as _onTimeout] (../../../node_modules/jsdom/lib/jsdom/browser/Window.js:552:19)
```

This happens because `done` promise fails before the promise returned by `.add()`, which happens before the `await tx.done` line — and as a result, at this point in time, the `done` promise doesn't have any `catch()` handlers, which causes promise rejection to bubble up.

As a fix, I changed all of our usage to this:

```Typescript
try {
  const tx = db.transaction(storeName, "readwrite");
  await Promise.all([tx.store.add(value), tx.done])
} catch (error) {
  console.error(error); // we expect the errors to be caught here
}
```

This solves the problem. However, when I shared this with the team, everybody found this **very confusing** and unintuitive, and I think it makes bad developer experience. Moreover, this is not mentioned anywhere in the docs.

**Describe the solution you'd like**

It happens because `done` promise is created immediately when transaction gets created:

https://github.com/jakearchibald/idb/blob/eb2fc14bb3588d09aaa5e86a83bf3519b06e10b3/src/wrap-idb-value.ts#L95

Instead of this, I would suggest to change done from property to a method, and create (or retrieve from cache) this promise only when method is called. This, of course, would be a breaking change, but I think it would greatly improve DX and prevent the worst kind of errors: hidden errors throwing outside of the normal execution stack, which most developers don't test for.

**Comment by golergka** [comment]
Just for the record, I encountered it while mocking indexed-db with [fake-indexeddb](https://www.npmjs.com/package/fake-indexeddb). It's theoretically possible this issue only surfaces with this mock and not real implementation because of different order of events. However, order of events is not part of the official IndexedDB specification anyway, so it shouldn't be relied on for correctness and DX.

**Comment by bogacg** [comment]
> Moreover, this is not mentioned anywhere in the docs.
How about this section in the [README.md](https://github.com/jakearchibald/idb?tab=readme-ov-file#txdone)?

**Comment by Shaghal** [comment]
Most errors, even when they're handled throw an `AbortError`
the issue is here:
- [promisifyRequest](https://github.com/jakearchibald/idb/blob/main/src/wrap-idb-value.ts#L57) 
- and [cacheDonePromiseForTransaction](https://github.com/jakearchibald/idb/blob/main/src/wrap-idb-value.ts#L71C10-L71C40) 

A temporary solution would be to change this:
```js
    const error = () => {
      reject(tx.error || new DOMException('AbortError', 'AbortError'));
      unlisten();
    };
```

to this:

```js
    const error = (error) => {
      reject(error || tx.error || new DOMException('AbortError', 'AbortError'));
      unlisten();
    };
```
And then handle it in your code. At least you'd know where the error actually happened

I created another [issue](https://github.com/jakearchibald/idb/issues/334) with more details.

**Comment by masonicboom** [comment]
Thanks for doing the detailed writeup @golergka. This is especially a problem on iOS when WebKit suspends and aborts transactions (https://github.com/jakearchibald/idb/pull/338#issuecomment-3491904991).
