### ISSUE TITLE
ReferenceError: IDBDatabase is not defined

### ISSUE THREAD

**Issue by steida** [jakearchibald/idb#87]
Not sure whether branch 4.0.0 is ok to be used in package.json dependencies `"idb": "https://github.com/jakearchibald/idb.git#4.0.0"`

But that's what I got: 

```
✔ Client: Compiled successfully in 417.98ms                webpackbar 03:14:04
 |  DONE  Compiled successfully in 489ms03:14:04
 |
 | ✔ Server: Compiled successfully in 564.50ms                webpackbar 03:14:04
 | ReferenceError: IDBDatabase is not defined
 |     at /Users/steida/dev/actualtasks/node_modules/idb/build/idb.js:4:32
 |     at Object.<anonymous> (/Users/steida/dev/actualtasks/node_modules/idb/build/idb.js:185:2)
 |     at Module._compile (module.js:652:30)
 |     at Object.Module._extensions..js (module.js:663:10)
 |     at Module.load (module.js:565:32)
 |     at tryModuleLoad (module.js:505:12)
 |     at Function.Module._load (module.js:497:3)
 |     at Module.require (module.js:596:17)
 |     at require (packages/web/internal/module.js:11:18)
 |     at Object.idb (/Users/steida/dev/actualtasks/packages/web/.packages/web/next/server/static/development/pages/_app.js:2841:18)
 |     at __webpack_require__ (/Users/steida/dev/actualtasks/packages/web/.packages/web/next/server/static/development/pages/_app.js:23:31)
 |     at packages/web/Module../database/Database.ts (/Users/steida/dev/actualtasks/packages/web/.next/server/static/development/pages/_app.js:1765:61)
 |     at __webpack_require__ (/Users/steida/dev/actualt
```

It seems the problem is importing lib in Node.js

**Comment by steida** [comment]
Related to https://github.com/jakearchibald/idb/issues/86

**Comment by steida** [comment]
Not sure what is the right solution for that...

**Comment by steida** [comment]
Closing, because it's not related to this lib, but Next.js conditional build.

**Comment by steida** [comment]
I think it's bug.

**Comment by jakearchibald** [comment]
Yeah, I should add something so it doesn't throw until openDb() is called.

**Comment by jakearchibald** [comment]
But in general, the branch isn't ready, and I may make breaking changes (that's why I haven't released it yet).

**Comment by briannaneiderman** [comment]
Unfortunately, I think this is still a problem. Everything works until I hit "refresh" in the browser, and then I get the same error as shown in the original comment.

**Comment by jakearchibald** [comment]
Can you create a demo of the issue?
